# LA Crime Data

* Read the crime data for LA from https://data.lacity.org/A-Safe-City/Crime-Data-from-2010-to-Present/y8tr-7khq/data
* Take the data from year 2015-present
* Formatted the data with Type of crime, Date Occurred and crime count
* Store the formatted data in csv file

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

In [2]:

# File to Load
data_folder = 'C:/data/crime_date_raw/Los_Angeles_city/'
raw_file = data_folder + 'crime_data_LA_2015.csv'

# Read the File and store into Pandas Data Frames
la_df = pd.read_csv(raw_file)
la_df.head()

,Unnamed: 0,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,...,Weapon Description,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location
0,200416,809,01/17/2015,2015-01-16,2130,9,Van Nuys,938,510,VEHICLE - STOLEN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,6200 FULTON AV,NaN,"(34.1814, -118.4263)"
1,200455,150108522,03/11/2015,2015-03-11,1600,1,Central,143,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),...,NaN,IC,Invest Cont,442.0,NaN,NaN,NaN,5TH,BROADWAY,"(34.0481, -118.2507)"
2,201035,150109432,03/24/2015,2015-03-23,1800,1,Central,185,310,BURGLARY,...,NaN,IC,Invest Cont,310.0,998.0,NaN,NaN,1200 MAPLE AV,NaN,"(34.0388, -118.2574)"
3,201056,150109804,03/29/2015,2015-03-29,800,1,Central,111,510,VEHICLE - STOLEN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,800 N HILL ST,NaN,"(34.0628, -118.2395)"
4,201396,150114304,06/08/2015,2015-06-08,1015,1,Central,144,850,INDECENT EXPOSURE,...,NaN,IC,Invest Cont,850.0,NaN,NaN,NaN,400 S SPRING ST,NaN,"(34.0488, -118.2483)"

In [3]:
# Read the values from Crime Code Description
cats = la_df['Crime Code Description'].unique()

cats_df = pd.DataFrame({'Crime Code Description' : cats})
#Write the Crime Code Description in csv and then work in excel to group them by primary type
cats_df.to_csv('categories.csv')

Edit categories_key.csv

In [4]:
#Read the edited csv for the final category type
cat_keys = pd.read_csv('categories_key.csv')
# Mearge the original dataframe with the new categories key 
la_short_cats = pd.merge(la_df, cat_keys, on='Crime Code Description')

In [5]:
la_short_cats.head()

,Unnamed: 0,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,...,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,Categories Final,Unnamed: 2,Unnamed: 3
0,200416,809,01/17/2015,2015-01-16,2130,9,Van Nuys,938,510,VEHICLE - STOLEN,...,510.0,NaN,NaN,NaN,6200 FULTON AV,NaN,"(34.1814, -118.4263)",MOTOR VEHICLE THEFT,NaN,NaN
1,201056,150109804,03/29/2015,2015-03-29,800,1,Central,111,510,VEHICLE - STOLEN,...,510.0,NaN,NaN,NaN,800 N HILL ST,NaN,"(34.0628, -118.2395)",MOTOR VEHICLE THEFT,NaN,NaN
2,201520,150115324,06/24/2015,2015-06-23,2230,1,Central,135,510,VEHICLE - STOLEN,...,510.0,NaN,NaN,NaN,200 S MAIN ST,NaN,"(34.051, -118.2445)",MOTOR VEHICLE THEFT,NaN,NaN
3,202662,150116489,07/11/2015,2015-07-10,2100,1,Central,192,510,VEHICLE - STOLEN,...,510.0,NaN,NaN,NaN,1300 MARGO ST,NaN,"(34.0386, -118.2638)",MOTOR VEHICLE THEFT,NaN,NaN
4,204878,150116490,07/11/2015,2015-07-10,2100,1,Central,162,510,VEHICLE - STOLEN,...,510.0,NaN,NaN,NaN,700 S HILL ST,NaN,"(34.0462, -118.2585)",MOTOR VEHICLE THEFT,NaN,NaN

In [7]:
crimes = la_short_cats['Categories Final'].unique()

# Add columns for each crime category, 0 = crime is not this category, 1 = crime is this category
for c in crimes:
    la_short_cats[c] = la_short_cats['Categories Final'].apply(lambda s: int(s==c))

In [8]:
# Group by date and export the counts to csv
LA_by_date = la_short_cats.groupby(['Date Occurred'])
LA_by_date[crimes].sum().to_csv('LA_by_date.csv')

In [9]:
LA_by_date.head()

,Unnamed: 0,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,...,BURGLARY,MISC,FRAUD,LARCENY-THEFT,AGGRAVATED ASSAULT,RAPE,ATTEMPT,ARSON,MURDER AND NON-NEGLIGENT MANSLAUGHTER,DRUG OFFENSE
0,200416,809,01/17/2015,2015-01-16,2130,9,Van Nuys,938,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
1,201056,150109804,03/29/2015,2015-03-29,800,1,Central,111,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
2,201520,150115324,06/24/2015,2015-06-23,2230,1,Central,135,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
3,202662,150116489,07/11/2015,2015-07-10,2100,1,Central,192,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
4,204878,150116490,07/11/2015,2015-07-10,2100,1,Central,162,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
5,205040,150116494,07/11/2015,2015-07-11,1200,1,Central,142,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
6,205101,150116696,07/14/2015,2015-07-13,1400,1,Central,171,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
7,653349,150128751,12/31/2015,2015-12-30,1600,1,Central,111,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
8,979604,150115675,06/29/2015,2015-06-28,1730,1,Central,185,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
9,979663,150307045,02/21/2015,2015-02-19,1500,3,Southwest,356,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
10,979802,150411088,06/17/2015,2015-06-17,400,4,Hollenbeck,424,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
11,979846,150125362,11/14/2015,2015-11-13,1300,1,Central,133,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
12,980013,150113111,05/20/2015,2015-05-19,1830,1,Central,182,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
13,980090,150506835,03/05/2015,2015-03-04,2200,5,Harbor,557,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
14,980461,150508750,04/18/2015,2015-04-17,2120,5,Harbor,529,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
15,980562,150511881,06/30/2015,2015-06-30,200,5,Harbor,507,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
16,980967,150615034,06/23/2015,2015-06-22,2230,6,Hollywood,667,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
17,980988,150616649,07/19/2015,2015-07-19,922,6,Hollywood,663,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
18,980996,150106918,02/16/2015,2015-02-15,2000,1,Central,111,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
19,981090,150206733,02/20/2015,2015-02-19,2130,2,Rampart,236,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
20,981159,150116573,07/12/2015,2015-07-11,2350,1,Central,135,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
21,981213,150218955,10/05/2015,2015-10-04,1920,2,Rampart,212,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
22,981294,150306316,02/09/2015,2015-02-08,1730,3,Southwest,318,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
23,981338,150113113,05/20/2015,2015-05-20,545,1,Central,122,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
24,981503,150116578,07/12/2015,2015-07-12,1820,1,Central,153,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
25,981731,150124296,11/01/2015,2015-10-30,1430,1,Central,182,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
26,981753,150210255,04/26/2015,2015-04-26,1150,2,Rampart,269,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
27,982136,150406922,03/08/2015,2015-03-07,1445,4,Hollenbeck,453,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
28,982177,150407061,03/11/2015,2015-03-10,900,4,Hollenbeck,406,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
29,982243,150126053,11/22/2015,2015-11-22,1500,1,Central,185,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55243,1686742,180107895,02/22/2018,2018-02-22,600,1,Central,182,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55256,1686919,180206680,02/19/2018,2018-02-18,1540,2,Rampart,291,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55257,1686928,180206697,02/20/2018,2018-02-19,2000,2,Rampart,245,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55258,1686931,180206845,02/22/2018,2018-02-21,2030,2,Rampart,299,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55260,1686953,180206760,02/21/2018,2018-02-20,2300,2,Rampart,245,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55261,1686975,180206806,02/21/2018,2018-02-21,1100,2,Rampart,221,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55262,1686993,180206849,02/22/2018,2018-02-21,2200,2,Rampart,246,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55263,1686995,180206854,02/22/2018,2018-02-21,2100,2,Rampart,241,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55264,1687002,180206864,02/22/2018,2018-02-21,600,2,Rampart,237,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55265,1687003,180206865,02/22/2018,2018-02-22,700,2,Rampart,231,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55268,1687155,180307166,02/18/2018,2018-02-18,200,3,Southwest,334,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55272,1687201,180307230,02/18/2018,2018-02-18,2230,3,Southwest,363,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55273,1687224,180307270,02/19/2018,2018-02-18,1400,3,Southwest,328,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55274,1687227,180307281,02/19/2018,2018-02-19,100,3,Southwest,363,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55278,1687267,180307364,02/20/2018,2018-02-20,1220,3,Southwest,363,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55281,1687341,180307476,02/22/2018,2018-02-22,100,3,Southwest,325,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55282,1687347,180307487,02/22/2018,2018-02-22,345,3,Southwest,359,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55283,1687348,180307488,02/22/2018,2018-02-22,200,3,Southwest,374,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55285,1687394,180307579,02/24/2018,2018-02-24,110,3,Southwest,393,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55307,1687539,180406202,02/19/2018,2018-02-19,1915,4,Hollenbeck,443,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55309,1687550,180406217,02/20/2018,2018-02-19,2045,4,Hollenbeck,438,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55351,1687834,180506466,02/23/2018,2018-02-23,1200,5,Harbor,557,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55352,1687838,180506505,02/24/2018,2018-02-23,1900,5,Harbor,506,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55353,1687839,180506522,02/24/2018,2018-02-23,2200,5,Harbor,506,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55355,1687841,180506525,02/24/2018,2018-02-24,30,5,Harbor,503,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55371,1688139,180607062,02/24/2018,2018-02-23,300,6,Hollywood,637,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55394,1688690,180806547,02/24/2018,2018-02-23,1800,8,West LA,898,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55594,1691022,181706597,02/24/2018,2018-02-24,200,17,Devonshire,1772,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
55595,1691023,181706599,02/24/2018,2018-02-24,330,17,Devonshire,1759,510,VEHICLE - STOLEN,...,0,0,0,0,0,0,0,0,0,0
74766,1686772,180108038,02/24/2018,2018-02-24,1315,1,Central,162,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),...,0,0,0,0,0,0,0,0,0,0